### Basic Post
GET http://localhost:8000/example/posts/12
Authorization: Bearer {{access_token}}

### Update Post
PUT http://localhost:8000/example/posts/12
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "title": "New Todo Title",
    "completed": true
}

### Create Post
POST http://localhost:8000/example/posts
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
    "title": "New Todo Title",
    "completed": true
}
